/****** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT OR YOUR CHANGES WILL BE OVERWRITTEN! ******/
#pragma once
/**	@file wa_api_json_keys.h
 *	@brief Defines the JSON object keys used for json_in and json_out values.
 *	@defgroup waapi_json_keys JSON object key
 */

/**
 *	@brief Defines our 'category' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CATEGORY L"category"

/**
 *	@brief Defines our 'categories' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CATEGORIES L"categories"

/**
 *	@brief Defines our 'result' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RESULT L"result"

/**
 *	@brief Defines our 'results' key for multiple results
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RESULTS L"results"

/**
 *	@brief Defines our 'timing' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TIME L"timing"

/**
 *	@brief Defines our 'timing' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TIMING L"timing"

/**
 *	@brief Defines our 'timestamp' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TIMESTAMP L"timestamp"

/**
 *	@brief Defines our 'error_code' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ERROR_CODE L"error_code"

/**
 *	@brief Defines our 'error_trace' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ERROR_TRACE L"error_trace"

/**
 *	@brief Defines our 'error_description' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ERROR_DESCRIPTION L"error_description"

/**
 *	@brief Defines our 'id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ID L"id"

/**
 *	@brief Defines our 'name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NAME L"name"

/**
 *	@brief Defines our 'versions' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VERSIONS L"versions"

/**
 *	@brief Defines our 'vendor_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VENDOR_ID L"vendor_id"

/**
 *	@brief Defines our 'vendor_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VENDOR_NAME L"vendor_name"

/**
 *	@brief Defines our 'product_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PRODUCT_ID L"product_id"

/**
 *	@brief Defines our 'product_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PRODUCT_NAME L"product_name"

/**
 *	@brief Defines our 'running' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RUNNING L"running"

/**
 *	@brief Defines our 'directories' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DIRECTORIES L"directories"

/**
 *	@brief Defines our 'components' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COMPONENTS L"components"

/**
 *	@brief Defines our 'path' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PATH L"path"

/**
 *	@brief Defines our 'paths' key which refers to one or more paths
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PATHS L"paths"

/**
 *	@brief Defines our 'path_existing' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PATH_EXISTING L"path_existing"

/**
 *	@brief Defines our 'path_new' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PATH_NEW L"path_new"

/**
 *	@brief Defines our 'version' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VERSION L"version"

/**
 *	@brief Defines our 'build_version' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_BUILD_VERSION L"build_version"

/**
 *	@brief Defines our 'build' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_BUILD L"build"

/**
 *	@brief Defines our 'description' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DESCRIPTION L"description"

/**
 *	@brief Defines our 'uninstall' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_UNINSTALL L"uninstall"

/**
 *	@brief Defines our 'authentic' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_AUTHENTIC L"authentic"

/**
 *	@brief Defines our 'hash_binary' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_HASH_BINARY L"hash_binary"

/**
 *	@brief Defines our 'details' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DETAILS L"details"

/**
 *	@brief Defines our 'status' key for use in details
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_STATUS L"status"

/**
 *	@brief Defines our 'file' key for use in details
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FILE L"file"

/**
 *	@brief Defines our 'sha256' key for use in details
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SHA256 L"sha256"

/**
 *	@brief Defines our 'certificate_info' key for use in details
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CERTIFICATE_INFO L"certificate_info"

/**
 *	@brief Defines our 'issuer' key for use in certificate_info
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ISSUER L"issuer"

/**
 *	@brief Defines our 'subject' key for use in certificate_info
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SUBJECT L"subject"

/**
 *	@brief Defines our 'valid_from' key for use in certificate_info
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VALID_FROM L"valid_from"

/**
 *	@brief Defines our 'valid_to' key for use in certificate_info
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VALID_TO L"valid_to"

/**
 *	@brief Defines our 'serial_number' key for use in certificate_info
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SERIAL_NUMBER L"serial_number"

/**
 *	@brief Defines our 'thumbprint' key for use in certificate_info
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_THUMBPRINT L"thumbprint"

/**
 *	@brief Defines our 'configs' key for returning multiple configs (by wa_api_setup)
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CONFIGURATIONS L"configs"

/**
 *	@brief Defines our 'config' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CONFIGURATION L"config"

/**
 *	@brief Defines our 'errors' key for returning multiple errors (by wa_api_setup)
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ERRORS L"errors"

/**
 *	@brief Defines our 'error' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ERROR L"error"

/**
 *	@brief Defines our 'define' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEFINE L"define"

/**
 *	@brief Defines our 'teardown' key (for invoking teardown via wa_api_invoke)
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TEARDOWN L"teardown"

/**
 *	@brief Defines our 'input' key (for json input to wa_api_invoke)
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INPUT L"input"

/**
 *	@brief Defines our 'inputs' key (for json input to wa_api_invoke) for multiple inputs
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INPUTS L"inputs"

/**
 *	@brief Defines our 'method' key (for passing method id to wa_api_invoke)
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METHOD L"method"

/**
 *	@brief Defines our 'module' key (for identifying modules when returning multiple resutls/errors from wa_api_setup)
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MODULE L"module"

/**
 *	@brief Defines our 'code' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CODE L"code"

/**
 *	@brief Defines our 'detected_product' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DETECTED_PRODUCT L"detected_product"

/**
 *	@brief Defines our 'detected_products' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DETECTED_PRODUCTS L"detected_products"

/**
 *	@brief Defines our 'company_name' key for use in details
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COMPANY_NAME L"company_name"

/**
 *	@brief Defines our 'license' key for use in details
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LICENSE L"license"

/**
 *	@brief Defines our 'enabled' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ENABLED L"enabled"

/**
 *	@brief Defines our 'antivirus' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ANTIVIRUS L"antivirus"

/**
 *	@brief Defines our 'antispyware' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ANTISPYWARE L"antispyware"

/**
 *	@brief Defines our 'is_recent' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_IS_RECENT L"is_recent"

/**
 *	@brief Defines our 'signature' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SIGNATURE L"signature"

/**
 *	@brief Defines our 'sig_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SIGNATURE_NAME L"sig_name"

/**
 *	@brief Defines our 'product' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PRODUCT L"product"

/**
 *	@brief Defines our 'vendor' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VENDOR L"vendor"

/**
 *	@brief Defines our 'main' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MAIN L"main"

/**
 *	@brief Defines our 'type' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TYPE L"type"

/**
 *	@brief Defines our 'timeframe' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TIMEFRAME L"timeframe"

/**
 *	@brief Defines our 'definitions' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEFINITIONS L"definitions"

/**
 *	@brief Defines our 'engine_version' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ENGINE_VERSION L"engine_version"

/**
 *	@brief Defines our 'last_update' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LAST_UPDATE L"last_update"

/**
 *	@brief Defines our 'source_time' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SOURCE_TIME L"source_time"

/**
 *	@brief Defines our 'last_threat_time' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LAST_THREAT_TIME L"last_threat_time"

/**
 *	@brief Defines our 'no_threats' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NO_THREATS L"no_threats"

/**
 *	@brief Defines our 'threats' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_THREATS L"threats"

/**
 *	@brief Defines our 'threat_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_THREAT_NAME L"threat_name"

/**
 *	@brief Defines our 'scan_time' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SCAN_TIME L"scan_time"

/**
 *	@brief Defines our 'remediation' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REMEDIATION L"remediation"

/**
 *	@brief Defines our 'scan_type' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SCAN_TYPE L"scan_type"

/**
 *	@brief Defines our 'malware_found' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MALWARE_FOUND L"malware_found"

/**
 *	@brief Defines our 'clean' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CLEAN L"clean"

/**
 *	@brief Defines our 'last_backup_activity' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LAST_BACKUP_ACTIVITY L"last_backup_activity"

/**
 *	@brief Defines our 'backups' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_BACKUPS L"backups"

/**
 *	@brief Defines our 'time_started' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TIME_STARTED L"time_started"

/**
 *	@brief Defines our 'time_ended' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TIME_ENDED L"time_ended"

/**
 *	@brief Defines our 'device' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEVICE L"device"

/**
 *	@brief Defines our 'destination' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DESTINATION L"destination"

/**
 *	@brief Defines our 'fully_encrypted' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FULLY_ENCRYPTED L"fully_encrypted"

/**
 *	@brief Defines our 'encryption_active' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ENCRYPTION_ACTIVE L"encryption_active"

/**
 *	@brief Defines our 'locations' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LOCATIONS L"locations"

/**
 *	@brief Defines our 'state' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_STATE L"state"

/**
 *	@brief Defines our 'algorithm' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ALGORITHM L"algorithm"

/**
 *	@brief Defines our 'strength' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_STRENGTH L"strength"

/**
 *	@brief Defines our 'is_default' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_IS_DEFAULT L"is_default"

/**
 *	@brief Defines our 'is_current' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_IS_CURRENT L"is_current"

/**
 *	@brief Defines our 'feed_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FEED_ID L"feed_id"

/**
 *	@brief Defines our 'count_behind' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COUNT_BEHIND L"count_behind"

/**
 *	@brief Defines our 'def_date' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEF_DATE L"def_date"

/**
 *	@brief Defines our 'def_version' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEF_VERSION L"def_version"

/**
 *	@brief Defines our 'def_signature' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEF_SIGNATURE L"def_signature"

/**
 *	@brief Defines our 'metrics' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METRICS L"metrics"

/**
 *	@brief Defines our 'basic' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METRICS_BASIC L"basic"

/**
 *	@brief Defines our 'strict' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METRICS_STRICT L"strict"

/**
 *	@brief Defines our 'engine_latest' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METRICS_ENGINE_LATEST L"engine_latest"

/**
 *	@brief Defines our 'date_latest' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METRICS_DATE_LATEST L"date_latest"

/**
 *	@brief Defines our 'version_latest' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METRICS_VERSION_LATEST L"version_latest"

/**
 *	@brief Defines our 'version_age' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METRICS_VERSION_AGE L"version_age"

/**
 *	@brief Defines our 'tolerance' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TOLERANCE L"tolerance"

/**
 *	@brief Defines our 'is_defunct' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_IS_DEFUNCT L"is_defunct"

/**
 *	@brief Defines our 'remediation_link' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REMEDIATION_LINK L"remediation_link"

/**
 *	@brief Defines our 'remediations' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REMEDIATIONS L"remediations"

/**
 *	@brief Defines our 'labels' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LABELS L"labels"

/**
 *	@brief Defines our 'pua' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PUA L"pua"

/**
 *	@brief Defines our 'toolbar' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TOOLBAR L"toolbar"

/**
 *	@brief Defines our 'bloatware' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_BLOATWARE L"bloatware"

/**
 *	@brief Defines our 'adware' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ADWARE L"adware"

/**
 *	@brief Defines our 'architecture' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ARCHITECTURE L"architecture"

/**
 *	@brief Defines our 'windows_event_forwarding' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_WINDOWS_EVENT_FORWARDING L"windows_event_forwarding"

/**
 *	@brief Defines our 'os_architecture' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_OS_ARCHITECTURE L"os_architecture"

/**
 *	@brief Defines our 'os_type' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_OS_TYPE L"os_type"

/**
 *	@brief Defines our 'os_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_OS_ID L"os_id"

/**
 *	@brief Defines our 'service_pack' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SERVICE_PACK L"service_pack"

/**
 *	@brief Defines our 'computer_type' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COMPUTER_TYPE L"computer_type"

/**
 *	@brief Defines our 'host_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_HOST_NAME L"host_name"

/**
 *	@brief Defines our 'reset' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RESET L"reset"

/**
 *	@brief Defines our 'expiration' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_EXPIRATION L"expiration"

/**
 *	@brief Defines our 'expired' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_EXPIRED L"expired"

/**
 *	@brief Defines our 'licensed' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LICENSED L"licensed"

/**
 *	@brief Defines our 'detection' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DETECTION L"detection"

/**
 *	@brief Defines our 'constant' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CONSTANT L"constant"

/**
 *	@brief Defines our 'local' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LOCAL L"local"

/**
 *	@brief Defines our 'manageability' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MANAGEABILITY L"manageability"

/**
 *	@brief Defines our 'vulnerability' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VULNERABILITY L"vulnerability"

/**
 *	@brief Defines our 'removal' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REMOVAL L"removal"

/**
 *	@brief Defines our 'deviceinfo' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEVICEINFO L"deviceinfo"

/**
 *	@brief Defines our 'driver' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DRIVER L"driver"

/**
 *	@brief Defines our 'advancedbrowser' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ADVBROWSER L"advancedbrowser"

/**
 *	@brief Defines our 'infection' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INFECTION L"infection"

/**
 *	@brief Defines our 'addon' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ADDON L"addon"

/**
 *	@brief Defines our 'netscan' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN L"netscan"

/**
 *	@brief Defines our 'debug' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEBUG L"debug"

/**
 *	@brief Defines our 'dlp' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DLP L"dlp"

/**
 *	@brief Defines our '3rdparty' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_3RDPARTY L"3rdparty"

/**
 *	@brief Defines our 'diagnostics' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DIAGNOSTICS L"diagnostics"

/**
 *	@brief Defines our 'model' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MODEL L"model"

/**
 *	@brief Defines our 'manufacturer' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MANUFACTURER L"manufacturer"

/**
 *	@brief Defines our 'max_speed_mhz' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MAXSPEEDMHZ L"max_speed_mhz"

/**
 *	@brief Defines our 'cpu' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CPU L"cpu"

/**
 *	@brief Defines our 'total_memory_mb' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TOTAL_MEMORY_MB L"total_memory_mb"

/**
 *	@brief Defines our 'memory_speed_mhz' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MEMORY_SPEED_MHZ L"memory_speed_mhz"

/**
 *	@brief Defines our 'memory' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MEMORY L"memory"

/**
 *	@brief Defines our 'network_adapters' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETWORK_ADAPTERS L"network_adapters"

/**
 *	@brief Defines our 'video_cards' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VIDEO_CARDS L"video_cards"

/**
 *	@brief Defines our 'disk_space' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DISK_SPACE L"disk_space"

/**
 *	@brief Defines our 'total_size_mb' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TOTAL_SIZE_MB L"total_size_mb"

/**
 *	@brief Defines our 'free_space_size_mb' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FREE_SPACE_SIZE_MB L"free_space_size_mb"

/**
 *	@brief Defines our 'get_current_config' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_GET_CURRENT_CONFIG L"get_current_config"

/**
 *	@brief Defines our 'reset_defaults' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RESET_DEFAULTS L"reset_defaults"

/**
 *	@brief Defines our 'os_language' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_OS_LANGUAGE L"os_language"

/**
 *	@brief Defines our 'methods' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METHODS L"methods"

/**
 *	@brief Defines our 'force_update' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FORCE_UPDATE L"force_update"

/**
 *	@brief Defines our 'refresh' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REFRESH L"refresh"

/**
 *	@brief Defines our 'license_retrieved' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LICENSE_RETRIEVED L"license_retrieved"

/**
 *	@brief Defines our 'operation' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_OPERATION L"operation"

/**
 *	@brief Defines our 'run_detection' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RUN_DETECTION L"run_detection"

/**
 *	@brief Defines our 'plugin' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PLUGIN L"plugin"

/**
 *	@brief Defines our 'protected' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PROTECTED L"protected"

/**
 *	@brief Defines our 'protected_info' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PROTECTED_INFO L"protected_info"

/**
 *	@brief Defines our 'adapter_enabled' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ADAPTER_ENABLED L"adapter_enabled"

/**
 *	@brief Defines our 'media_state' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MEDIA_STATE L"media_state"

/**
 *	@brief Defines our 'default_gateways' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEFAULT_GATEWAYS L"default_gateways"

/**
 *	@brief Defines our 'physical_address' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PHYSICAL_ADDRESS L"physical_address"

/**
 *	@brief Defines our 'ipv4_addresses' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_IPV4_ADDRESSES L"ipv4_addresses"

/**
 *	@brief Defines our 'ipv6_addresses' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_IPV6_ADDRESSES L"ipv6_addresses"

/**
 *	@brief Defines our 'dhcp_enabled' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DHCP_ENABLED L"dhcp_enabled"

/**
 *	@brief Defines our 'subnet_masks' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SUBNET_MASKS L"subnet_masks"

/**
 *	@brief Defines our 'dhcp_lease_obtained' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DHCP_LEASE_OBTAINED L"dhcp_lease_obtained"

/**
 *	@brief Defines our 'dhcp_lease_expires' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DHCP_LEASE_EXPIRES L"dhcp_lease_expires"

/**
 *	@brief Defines our 'dhcp_server_address' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DHCP_SERVER_ADDRESS L"dhcp_server_address"

/**
 *	@brief Defines our 'dns_server_addresses' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DNS_SERVER_ADDRESSES L"dns_server_addresses"

/**
 *	@brief Defines our 'device_uuid' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEVICE_UUID L"device_uuid"

/**
 *	@brief Defines our 'device_identity' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEVICE_IDENTITY L"device_identity"

/**
 *	@brief Defines our 'title' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TITLE L"title"

/**
 *	@brief Defines our 'severity' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SEVERITY L"severity"

/**
 *	@brief Defines our 'security_update_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SECURITY_UPDATE_ID L"security_update_id"

/**
 *	@brief Defines our 'kb_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_KB_ID L"kb_id"

/**
 *	@brief Defines our 'patches' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PATCHES L"patches"

/**
 *	@brief Defines our 'threads' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_THREADS L"threads"

/**
 *	@brief Defines our 'install_from_cache' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INSTALL_FROM_CACHE L"install_from_cache"

/**
 *	@brief Defines our 'is_virtual' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_IS_VIRTUAL L"is_virtual"

/**
 *	@brief Defines our 'vm_path' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VM_PATH L"vm_path"

/**
 *	@brief Defines our 'vm_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VM_NAME L"vm_name"

/**
 *	@brief Defines our 'virtual_machines' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VIRTUAL_MACHINES L"virtual_machines"

/**
 *	@brief Defines our 'vm_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VM_ID L"vm_id"

/**
 *	@brief Defines our 'hypervisor_type' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_HYPERVISOR_TYPE L"hypervisor_type"

/**
 *	@brief Defines our 'snapshot_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SNAPSHOT_NAME L"snapshot_name"

/**
 *	@brief Defines our 'action' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ACTION L"action"

/**
 *	@brief Defines our 'record' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RECORD L"record"

/**
 *	@brief Defines our 'restore' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RESTORE L"restore"

/**
 *	@brief Defines our 'run' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RUN L"run"

/**
 *	@brief Defines our 'shut_down' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SHUT_DOWN L"shut_down"

/**
 *	@brief Defines our 'suspend' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VM_SUSPEND L"suspend"

/**
 *	@brief Defines our 'attempt_synchronize' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ATTEMPT_SYNCHRONIZE L"attempt_synchronize"

/**
 *	@brief Defines our 'suspended' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SUSPENDED L"suspended"

/**
 *	@brief Defines our 'get_version' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_GET_VERSION L"get_version"

/**
 *	@brief Defines our 'metascan_api_key' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METASCAN_API_KEY L"metascan_api_key"

/**
 *	@brief Defines our 'cookies' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COOKIES L"cookies"

/**
 *	@brief Defines our 'cookie_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COOKIE_NAME L"cookie_name"

/**
 *	@brief Defines our 'cookie_value' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COOKIE_VALUE L"cookie_value"

/**
 *	@brief Defines our 'cookie_expire_time' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COOKIE_EXPIRE_TIME L"cookie_expire_time"

/**
 *	@brief Defines our 'cookie_url' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COOKIE_URL L"cookie_url"

/**
 *	@brief Defines our 'cookie_name_contain' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COOKIE_NAME_CONTAIN L"cookie_name_contain"

/**
 *	@brief Defines our 'cookie_url_contain' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COOKIE_URL_CONTAIN L"cookie_url_contain"

/**
 *	@brief Defines our 'cookie_base_domain' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COOKIE_BASE_DOMAIN L"cookie_base_domain"

/**
 *	@brief Defines our 'start_time' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_START_TIME L"start_time"

/**
 *	@brief Defines our 'end_time' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_END_TIME L"end_time"

/**
 *	@brief Defines our 'delete_all' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DELETE_ALL L"delete_all"

/**
 *	@brief Defines our 'secure_delete' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SECURE_DELETE L"secure_delete"

/**
 *	@brief Defines our 'filter' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FILTER L"filter"

/**
 *	@brief Defines our 'target_path' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TARGET_PATH L"target_path"

/**
 *	@brief Defines our 'target_volume' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TARGET_VOLUME L"target_volume"

/**
 *	@brief Defines our 'last_modified_time' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LAST_MODIFIED_TIME L"last_modified_time"

/**
 *	@brief Defines our 'product_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PRODUCT_NAME L"product_name"

/**
 *	@brief Defines our 'installed_for_all_users' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INSTALLED_FOR_ALL_USERS L"installed_for_all_users"

/**
 *	@brief Defines our 'detect_user_installed_mode' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DETECT_USER_INSTALLED_MODE L"detect_user_installed_mode"

/**
 *	@brief Defines our 'install_directories' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INSTALL_DIRECTORIES L"install_directories"

/**
 *	@brief Defines our 'running_processes' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RUNNING_PROCESSES L"running_processes"

/**
 *	@brief Defines our 'estimated_size_mb' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ESTIMATED_SIZE_MB L"estimated_size_mb"

/**
 *	@brief Defines our 'install_date' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INSTALL_DATE L"install_date"

/**
 *	@brief Defines our 'process_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PROCESS_ID L"process_id"

/**
 *	@brief Defines our 'file_path' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FILE_PATH L"file_path"

/**
 *	@brief Defines our 'returned_at' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RETURNED_AT L"returned_at"

/**
 *	@brief Defines our 'message' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MESSAGE L"message"

/**
 *	@brief Defines our 'called_at' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CALLED_AT L"called_at"

/**
 *	@brief Defines our 'value' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VALUE L"value"

/**
 *	@brief Defines our 'target_process_ids' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TARGET_PROCESS_IDS L"target_process_ids"

/**
 *	@brief Defines our 'scan_all_running_processes' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SCAN_ALL_RUNNING_PROCESSES L"scan_all_running_processes"

/**
 *	@brief Defines our 'scan_level' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SCAN_LEVEL L"scan_level"

/**
 *	@brief Defines our 'force_rescan' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FORCE_RESCAN L"force_rescan"

/**
 *	@brief Defines our 'infection_scan_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INFECTION_SCAN_ID L"infection_scan_id"

/**
 *	@brief Defines our 'target_addresses' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TARGET_ADDRESSES L"target_addresses"

/**
 *	@brief Defines our 'scan_all_connected_addresses' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SCAN_ALL_CONNECTED_ADDRESSES L"scan_all_connected_addresses"

/**
 *	@brief Defines our 'scan_complete' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SCAN_COMPLETE L"scan_complete"

/**
 *	@brief Defines our 'scan_complete' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SCAN_COMPLETE L"scan_complete"

/**
 *	@brief Defines our 'total_source' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TOTAL_SOURCE L"total_source"

/**
 *	@brief Defines our 'hash' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_HASH L"hash"

/**
 *	@brief Defines our 'explanation' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_EXPLANATION L"explanation"

/**
 *	@brief Defines our 'av_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_AV_NAME L"av_name"

/**
 *	@brief Defines our 'av_def_time' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_AV_DEF_TIME L"av_def_time"

/**
 *	@brief Defines our 'assessment' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_AV_ASSESSMENT L"assessment"

/**
 *	@brief Defines our 'source_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SOURCE_NAME L"source_name"

/**
 *	@brief Defines our 'confident' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CONFIDENT L"confident"

/**
 *	@brief Defines our 'geo_info' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_GEO_INFO L"geo_info"

/**
 *	@brief Defines our 'country_name' key in 'geo_info' 
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COUNTRY_NAME L"country_name"

/**
 *	@brief Defines our 'country_code' key in 'geo_info'
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COUNTRY_CODE_ISO2 L"iso2_code"

/**
 *	@brief Defines our 'friendly_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FRIENDLY_NAME L"friendly_name"

/**
 *	@brief Defines our 'region_name' key in 'geo_info'
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REGION_NAME L"region_name"

/**
 *	@brief Defines our 'region_code' key in 'geo_info'
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REGION_CODE L"region_code"

/**
 *	@brief Defines our 'city' key in 'geo_info'
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CITY L"city"

/**
 *	@brief Defines our 'files_in_archive' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FILES_IN_ARCHIVE L"files_in_archive"

/**
 *	@brief Defines our 'encrypted_result' key, for all returned encrypted data
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ENCRYPTED_RESULT L"encrypted_result"

/**
 *	@brief Defines our 'encrypted_input' key for input encrypted data
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ENCRYPTED_INPUT L"encrypted_input"

/**
 *	@brief Defines a query element for specifying the desired type of result
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_QUERY_RESULT_TYPE L"type"

/**
 *	@brief  Defines a query result format
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_QUERY_RESULT_FORMAT L"format"

/**
 *	@brief Defines the parameters used to query the OPSWAT vmod server
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_QUERY_PARAMS L"qparams"

/**
 *	@brief Defines uid information associated with an element
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_UID L"uid"

/**
 *	@brief Defines a collection of compliance indicators
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INDICATORS L"indicators"

/**
 *	@brief Defines a Definition Date indicator
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INDICATOR_DEF_DATE L"def_date"

/**
 *	@brief Defines a Definition Version indicator
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INDICATOR_DEF_VERSION L"def_version"

/**
 *	@brief Defines an Engine Version indicator
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INDICATOR_ENGINE_VERSION L"engine_version"

/**
 *	@brief Defines an Definition Signature indicator
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INDICATOR_DEF_SIGNATURE L"def_signature"

/**
 *	@brief Defines a version count metric
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METRICS_COUNT_BEHIND L"count_behind"

/**
 *	@brief Defines a version count metric (related to Internet Explorer)
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METRICS_COUNT_BEHIND_IE L"ie_count_behind"

/**
 *	@brief Defines a version count metric (related to .Net Framework)
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METRICS_COUNT_BEHIND_DOT_NET L"dot_net_count_behind"

/**
 *	@brief Defines the MetaDefender Endpoint Security SDK Monitor engine version metric
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METRICS_ENGINE_VERSION L"engine_version"

/**
 *	@brief Defines the contents of an MetaDefender Endpoint Security SDK Monitor uid feed
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_UID_HIST L"uid_hist"

/**
 *	@brief Defines the order of an element in a history with 1 the most recent
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_HIST L"hist"

/**
 *	@brief Defines a list of resource elements
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RESOURCE_LIST L"resource_list"

/**
 *	@brief Defines a list of uid elements
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_UID_LIST L"uid_list"

/**
 *	@brief Defines the version range of an element
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VERSION_RANGE L"version_range"

/**
 *	@brief Defines the parameters used to know status of data queried (from cache, live or in cache and expired)
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DATA_STATUS L"data_status"

/**
 *	@brief Defines the data returned by the API
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DATA L"data"

/**
 *	@brief Defines an Resource Object returned from a bulk query
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RESOURCES L"resources"

/**
 *	@brief Defines the parameter represent security interface
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DETECTION_INTERFACE L"detection_interface"

/**
 *	@brief Defines a query element that determines the 'history limit' of a metric
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_QUERY_HIST_LIMIT L"hist_limit"

/**
 *	@brief Defines our 'is_missing_service_pack' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_IS_MISSING_SERVICE_PACK L"is_missing_service_pack"

/**
 *	@brief Defines our 'am_type' key for anitmalware type
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_AM_TYPE L"am_type"

/**
 *	@brief Defines our 'include_services' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INCLUDE_SERVICES L"include_services"

/**
 *	@brief Defines our 'services' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SERVICES L"services"

/**
 *	@brief Defines our 'md5' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MD5 L"md5"

/**
 *	@brief Defines our 'async_job_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ASYNC_JOB_ID L"async_job_id"

/**
 *	@brief Defines our 'async_results' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ASYNC_RESULTS L"async_results"

/**
 *	@brief Defines our 'async_job' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ASYNC_JOB L"async_job"

/**
 *	@brief Defines our 'event_type' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_EVENT_TYPE L"event_type"

/**
 *	@brief Defines our 'binary_path' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_BINARY_PATH L"binary_path"

/**
 *	@brief Defines our 'command_line' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COMMAND_LINE L"command_line"

/**
 *	@brief Defines our 'install_location' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INSTALL_LOCATION L"install_location"

/**
 *	@brief Defines our 'handler_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_HANDLER_ID L"handler_id"

/**
 *	@brief Defines a specifier key to denote an individual property
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SPECIFIER L"specifier"

/**
 *	@brief Defines a 'username' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_USERNAME L"username"

/**
 *	@brief Defines a 'domain' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DOMAIN L"domain"

/**
 *	@brief Defines a key that's used to control whether processes should be scanned
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PROCESS_SCAN L"process_scan"

/**
 *	@brief Defines a key that's used to hold the process scanning options
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PROCESS_SCAN_OPTIONS L"process_scan_options"

/**
 *	@brief Defines a key that controls whether files should be uploaded to Metadefender
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NO_FILE_UPLOAD L"no_file_upload"

/**
 *	@brief Defines a key that controls whether infected files should be shared with antimalware vendors
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NO_SAMPLE_SHARING L"no_sample_sharing"

/**
 *	@brief Defines a key that controls whether network scan needs to be performed
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETWORK_CONNECTION_SCAN L"network_connection_scan"

/**
 *	@brief Defines a key that's used to hold the reated threat detection options
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REPEATED_THREAT_DETECTION_OPTIONS L"repeated_threat_detection_options"

/**
 *	@brief Defines a key that controls whether repeated threats should be detected
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REPEATED_THREAT_DETECTION L"repeated_threat_detection"

/**
 *	@brief Defines how many past days-worth of threats to consider for repeat threat detection
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MONITOR_DAYS L"monitor_days"

/**
 *	@brief Defines the minimum number of times the threat has to be detected to be considered a repeated threat
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REPEATED_TOLERANCE L"repeated_tolerance"

/**
 *	@brief Defines an input ipv4 address, network or range
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_IPV4_INPUT L"ipv4"

/**
 *	@brief Defines a set of method options
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_OPTIONS_INPUT L"options"

/**
 *	@brief Defines a list of ipv4 networks
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_IPV4_NETWORK_LIST L"ip_v4_net_list"

/**
 *	@brief Defines a list of ipv6 networks
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_IPV6_NETWORK_LIST L"ip_v6_net_list"

/**
 *	@brief Defines an ipv4 network
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_IPV4_NETWORK L"ip_v4_net"

/**
 *	@brief Defines an ipv6 network
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_IPV6_NETWORK L"ip_v6_net"

/**
 *	@brief Defines an ipv4 network size
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_IPV4_NETWORK_SIZE L"size"

/**
 *	@brief Defines an ip address count
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_COUNT L"size"

/**
 *	@brief Defines a list of ipv4 addresses
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_IPV4_LIST L"ip_v4_list"

/**
 *	@brief Defines a list of ipv6 addresses
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_IPV6_LIST L"ip_v6_list"

/**
 *	@brief Defines an ipv4 network address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_IPV4_ADDRESS L"ip_v4"

/**
 *	@brief Defines an ipv6 network address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_IPV6_ADDRESS L"ip_v6"

/**
 *	@brief Defines an ipv4 mac address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_MAC_ADDRESS L"mac"

/**
 *	@brief Defines an array of dns address strings
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_DNS L"dns"

/**
 *	@brief Defines a netscan hitcode
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_HITCODE L"hit_code"

/**
 *	@brief Defines a list of network interfaces
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_LIST L"interface_list"

/**
 *	@brief Defines a network interface id
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_ID L"interface_id"

/**
 *	@brief Defines a network interface description
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_DESCRIPTION L"interface_desc"

/**
 *	@brief Defines a network interface label
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_LABEL L"interface"

/**
 *	@brief Defines a network interface type
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_TYPE L"type"

/**
 *	@brief Defines a network download speed in kbps
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_DOWNLOAD_SPEED L"down_speed_kbps"

/**
 *	@brief Defines a network upload speed in kbps
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_UPLOAD_SPEED L"up_speed_kbps"

/**
 *	@brief Defines a MTU: Maximum transmisson Unit in bytes
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_MTU L"mtu"

/**
 *	@brief Defines a Primary DNS Suffix
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_PRIMARY_DNS_SUFFIX L"primary_dns_suffix"

/**
 *	@brief Defines if dynamic DNS is enabled
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_DYN_DNS_ENABLED L"dynamic_dns_enabled"

/**
 *	@brief Defines if DHCP enabled
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_DHCP_ENABLED L"dhcp_enabled"

/**
 *	@brief Defines if Netbios over tcpip enabled
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_NETBIOS_ENABLED L"netbios_over_tcpip_enabled"

/**
 *	@brief Defines if ipv4 is enabled
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV4_ENABLED L"ipv4_enabled"

/**
 *	@brief Defines if ipv6 is enabled
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV6_ENABLED L"ipv6_enabled"

/**
 *	@brief Defines a network interface connection status
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_CONNECTION_STATUS L"connected"

/**
 *	@brief Defines an ipv6 address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV6 L"ipv6"

/**
 *	@brief Defines an array of ipv6 addresses
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_SECONDARY_IPV6 L"secondary_ipv6"

/**
 *	@brief Defines an ipv6 multicast address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV6_MULTICAST L"ipv6_multicast"

/**
 *	@brief Defines an array of ipv6 multicast addresses
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_SECONDARY_IPV6_MULTICAST L"secondary_ipv6_multicast"

/**
 *	@brief Defines an ip6 gateway address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV6_GATEWAY L"ipv6_gateway"

/**
 *	@brief Defines an array of ip6 gateway address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_SECONDARY_IPV6_GATEWAY L"secondary_ipv6_gateway"

/**
 *	@brief Defines an ipv6 dns server address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV6_DNS_SERVER L"ipv6_dns_server"

/**
 *	@brief Defines an array of ipv6 dns server addresses
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_SECONDARY_IPV6_DNS_SERVER L"secondary_ipv6_dns_server"

/**
 *	@brief Defines an ipv6 dhcp server address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV6_DHCP_SERVER L"ipv6_dhcp_server"

/**
 *	@brief Defines a dhcpv6 client duid
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_DHCPV6_CLIENT_DUID L"dhcpv6_client_duid"

/**
 *	@brief Defines a dhcpv6 iaid
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_DHCPV6_IAID L"dhcpv6_iaid"

/**
 *	@brief Defines an ipv4 address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV4 L"ipv4"

/**
 *	@brief Defines an array of ipv4 addresses
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_SECONDARY_IPV4 L"secondary_ipv4"

/**
 *	@brief Defines an ipv4 multicast address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV4_MULTICAST L"ipv4_multicast"

/**
 *	@brief Defines an array of ipv4 multicast addresses
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_SECONDARY_IPV4_MULTICAST L"secondary_ipv4_multicast"

/**
 *	@brief Defines an ip4 gateway address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV4_GATEWAY L"ipv4_gateway"

/**
 *	@brief Defines an array of ip4 gateway addresses
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_SECONDARY_IPV4_GATEWAY L"secondary_ipv4_gateway"

/**
 *	@brief Defines an ip4 dns server address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV4_DNS_SERVER L"ipv4_dns_server"

/**
 *	@brief Defines an array of ip4 dns server addresses
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_SECONDARY_IPV4_DNS_SERVER L"secondary_ipv4_dns_server"

/**
 *	@brief Defines an ipv4 dhcp server address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV4_DHCP_SERVER L"ipv4_dhcp_server"

/**
 *	@brief Defines a temporary ipv6 address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_IPV6_TEMP L"ipv6_temp"

/**
 *	@brief Defines a link local ipv6 address
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_LINK_LOCAL_IPV6 L"link_local_ipv6"

/**
 *	@brief Defines an ipv4 network mask
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_MASK L"mask"

/**
 *	@brief Defines an array of ipv4 network masks
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_SECONDARY_MASK L"secondary_mask"

/**
 *	@brief Defines an ipv4 network in cidr notation
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_CIDR L"cidr"

/**
 *	@brief Defines an array of ipv4 networks in cidr notation
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INTERFACE_SECONDARY_CIDR L"secondary_cidr"

/**
 *	@brief Defines a string indicating number of packets to capture.
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_PACKETS L"no_of_packets"

/**
 *	@brief Defines a string indicating whether to perform OS detection
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_OS_DETECT L"os_detect"

/**
 *	@brief Defines a string containing manufacturer's name
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_OS_DETECT_MANUFACTURER L"device_manufacturer"

/**
 *	@brief Defines a string representing the type of the device
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_OS_DETECT_DEVICE_TYPE L"device_type"

/**
 *	@brief Defines a string containing the general description of the device
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_OS_DETECT_OS_DESC L"os_desc"

/**
 *	@brief Defines a number representing the type of device
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_OS_DETECT_OS_TYPE L"os_type"

/**
 *	@brief Defines an array of strings containing the names of possible operating systems
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_OS_DETECT_OS_DETAILS L"os_details"

/**
 *	@brief Defines an array of strings containing the guesses for names of possible operating systems
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_OS_DETECT_OS_GUESS L"os_guess"

/**
 *	@brief Defines a number representing the distance from the target
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_OS_DETECT_NETWORK_HOPS L"network_hops"

/**
 *	@brief Defines a boolean indicating whether to start netsh trace (Requires admin privilage).
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_NETSH_TRACE L"trace"

/**
 *	@brief Defines a boolean indicating whether to resolve dns for each ip/ipv6. MAY CAUSE CONSIDERABLE SLOW DOWN.
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_RESOLVE_DNS L"resolve_dns"

/**
 *	@brief Defines a number indicating the count of hosts detected.
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_HOST_COUNT L"count"

/**
 *	@brief Defines a string indicating a timestamp. Only fetches elements with timestamp less than or equal to this timestamp.
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_TIMESTAMP_FILTER_BEFORE L"before_ts"

/**
 *	@brief Defines a string indicating a timestamp. Only fetches elements with timestamp greater than or equal to this timestamp.
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_TIMESTAMP_FILTER_AFTER L"after_ts"

/**
 *	@brief Defines a string indicating a timestamp. Only fetches elements with initial timestamp less than or equal to this timestamp.
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INIT_TIMESTAMP_FILTER_BEFORE L"before_init_ts"

/**
 *	@brief Defines a string indicating a timestamp. Only fetches elements with initial timestamp greater than or equal to this timestamp.
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETSCAN_INIT_TIMESTAMP_FILTER_AFTER L"after_init_ts"

/**
 *	@brief Defines a string label key for an accompanying property; its meaning is typically derived from the context of the query
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LABEL L"label"

/**
 *	@brief Defines our 'resource_version' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RESOURCE_VERSION L"resource_version"

/**
 *	@brief Defines our 'interface' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INTERFACE L"interface"

/**
 *	@brief Defines our 'accessible' key (typically boolean value)
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ACCESSIBLE L"accessible"

/**
 *	@brief Defines our 'volumes' key, referring to one or more volumes
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VOLUMES L"volumes"

/**
 *	@brief Defines our 'inclusion_list' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INCLUSION_LIST L"inclusion_list"

/**
 *	@brief Defines our 'exclusion_list' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_EXCLUSION_LIST L"exclusion_list"

/**
 *	@brief Defines our 'uninstall_info' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_UNINSTALL_INFO L"uninstall_info"

/**
 *	@brief Defines our 'security_center' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SECURITY_CENTER L"security_center"

/**
 *	@brief Defines our 'namespace' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NAMESPACE L"namespace"

/**
 *	@brief Defines our 'guid' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_GUID L"guid"

/**
 *	@brief Defines our 'collect_system_info' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COLLECT_SYSTEM_INFO L"collect_system_info"

/**
 *	@brief Defines our 'collect_uninstall' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COLLECT_UNINSTALL L"collect_uninstall"

/**
 *	@brief Defines our 'collect_security_center' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COLLECT_SECURITY_CENTER L"collect_security_center"

/**
 *	@brief Defines our 'os' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_OS L"os"

/**
 *	@brief Defines our 'system_info' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SYSTEM_INFO L"system_info"

/**
 *	@brief Defines our 'output_file' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_OUTPUT_FILE L"output_file"

/**
 *	@brief Defines our 'output_file_format' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_OUPUT_FILE_FORMAT L"output_file_format"

/**
 *	@brief Defines our 'whitelisted_process_names' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_WHITELISTED_PROCESS_NAMES L"whitelisted_process_names"

/**
 *	@brief Defines our 'additional_process_names' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ADDITIONAL_PROCESS_NAMES L"additional_process_names"

/**
 *	@brief Defines our 'password' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PASSWORD L"password"

/**
 *	@brief Defines our 'single_threaded' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SINGLE_THREADED L"single_threaded"

/**
 *	@brief Defines our 'method_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_METHOD_NAME L"method_name"

/**
 *	@brief Defines our 'enable' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ENABLE L"enable"

/**
 *	@brief Defines our 'connected' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CONNECTED L"connected"

/**
 *	@brief Defines our 'encrypted' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ENCRYPTED L"encrypted"

/**
 *	@brief Defines our 'file_structure' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FILE_STRUCTURE L"file_structure"

/**
 *	@brief Defines our 'base_path' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_BASE_PATH L"base_path"

/**
 *	@brief Defines our 'files' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FILES L"files"

/**
 *	@brief Defines our 'folders' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FOLDERS L"folders"

/**
 *	@brief Defines our 'libraries' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LIBRARIES L"libraries"

/**
 *	@brief Defines our 'backup_path' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_BACKUP_PATH L"backup_path"

/**
 *	@brief Defines our 'registry' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REGISTRY L"registry"

/**
 *	@brief Defines our 'process_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PROCESS_NAME L"process_name"

/**
 *	@brief Defines our 'product_info' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PRODUCT_INFO L"product_info"

/**
 *	@brief Defines our 'netbios_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NETBIOS_NAME L"netbios_name"

/**
 *	@brief Defines our 'virtualization' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VIRTUALIZATION L"virtualization"

/**
 *	@brief Defines our 'recursive' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RECURSIVE L"recursive"

/**
 *	@brief Defines our 'size' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SIZE L"size"

/**
 *	@brief Defines our 'native' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NATIVE L"native"

/**
 *	@brief Defines our 'date' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DATE L"date"

/**
 *	@brief Defines our 'volume' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VOLUME L"volume"

/**
 *	@brief Defines our 'support_wde' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SUPPORT_WDE L"support_wde"

/**
 *	@brief Defines our 'disable_powershell' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DISABLE_POWERSHELL L"disable_powershell"

/**
 *	@brief Defines our 'no_hash_lookup' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_NO_HASH_LOOKUP L"no_hash_lookup"

/**
 *	@brief Defines our 'api_key' key, used only by infection module
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_API_KEY L"api_key"

/**
 *	@brief Defines our 'timeout' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_TIMEOUT L"timeout"

/**
 *	@brief Defines our 'reboot_required' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REBOOT_REQUIRED L"reboot_required"

/**
 *	@brief Defines our 'language' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LANGUAGE L"language"

/**
 *	@brief Defines our 'bitness' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_BITNESS L"bitness"

/**
 *	@brief Defines our 'add' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ADD L"add"

/**
 *	@brief Defines our 'remove' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REMOVE L"remove"

/**
 *	@brief Defines our 'modules' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MODULES L"modules"

/**
 *	@brief Defines our 'module_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MODULE_NAME L"module_name"

/**
 *	@brief Defines our 'uri' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_URI L"uri"

/**
 *	@brief Defines our 'displayName' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_WSC_DISPLAY_NAME L"displayName"

/**
 *	@brief Defines our 'instanceGuid' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_WSC_INSTANCE_GUID L"instanceGuid"

/**
 *	@brief Defines our 'productState' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_WSC_PRODUCT_STATE L"productState"

/**
 *	@brief Defines our 'productEnabled' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_WSC_PRODUCT_ENABLED L"productEnabled"

/**
 *	@brief Defines our 'productUpToDate' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_WSC_PRODUCT_UP_TO_DATE L"productUpToDate"

/**
 *	@brief Defines our 'pathToSignedProductExe' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_WSC_PATH_TO_SIGNED_PRODUCT_EXE L"pathToSignedProductExe"

/**
 *	@brief Defines our 'pathToSignedReportingExe' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_WSC_PATH_TO_SIGNED_REPORTING_EXE L"pathToSignedReportingExe"

/**
 *	@brief Defines our 'check_password_protection' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CHECK_PASSWORD_PROTECTION L"check_password_protection"

/**
 *	@brief Defines our digital signature 'signed' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DIGITAL_SIGNATURE_STATUS L"signed"

/**
 *	@brief Defines our 'verify_product_digital_signature' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_VERIFY_PRODUCT_DIGITAL_SIGNATURE L"verify_product_digital_signature"

/**
 *	@brief Defines our 'instances' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INSTANCES L"instances"

/**
 *	@brief Defines our 'instance_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_INSTANCE_ID L"instance_id"

/**
 *	@brief Defines our 'skip_connection_check' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SKIP_CONNECTION_CHECK L"skip_connection_check"

/**
 *	@brief Defines our 'protect_copy_paste' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PROTECT_COPY_PASTE L"protect_copy_paste"

/**
 *	@brief Defines our 'category_parent' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CATEGORY_PARENT L"category_parent"

/**
 *	@brief Defines our 'revision' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REVISION L"revision"

/**
 *	@brief Defines our 'category_id' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CATEGORY_ID L"category_id"

/**
 *	@brief Defines our 'category_description' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_CATEGORY_DESCRIPTION L"category_description"

/**
 *	@brief Defines our 'screen_lock_timeout' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SCREEN_LOCK_TIMEOUT L"screen_lock_timeout"

/**
 *	@brief Defines our 'uninstall_hive' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_UNINSTALL_HIVE L"uninstall_hive"

/**
 *	@brief Defines our 'show_uninstall_hive' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SHOW_UNINSTALL_HIVE L"show_uninstall_hive"

/**
 *	@brief Defines our 'KeyName' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REGISTRY_KEYNAME L"KeyName"

/**
 *	@brief Defines our 'DisplayName' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REGISTRY_DISPLAYNAME L"DisplayName"

/**
 *	@brief Defines our 'DisplayVersion' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REGISTRY_DISPLAYVERSION L"DisplayVersion"

/**
 *	@brief Defines our 'InstallLocation' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REGISTRY_INSTALLLOCATION L"InstallLocation"

/**
 *	@brief Defines our 'UninstallString' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REGISTRY_UNINSTALLSTRING L"UninstallString"

/**
 *	@brief Defines our 'InstallDate' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REGISTRY_INSTALLDATE L"InstallDate"

/**
 *	@brief Defines our 'ModifyPath' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REGISTRY_MODIFYPATH L"ModifyPath"

/**
 *	@brief Defines our 'Publisher' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PUBLISHER L"Publisher"

/**
 *	@brief Defines our 'bundle_info' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_BUNDLE_INFO L"bundle_info"

/**
 *	@brief Defines our 'show_bundle_info' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SHOW_BUNDLE_INFO L"show_bundle_info"

/**
 *	@brief Defines our 'CFBundleShortVersionString' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_BUNDLE_SHORT_VERSION_STRING L"CFBundleShortVersionString"

/**
 *	@brief Defines our 'optional' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_OPTIONAL L"optional"

/**
 *	@brief Defines our 'country' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COUNTRY L"country"

/**
 *	@brief Defines our 'coordinates' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COORDINATES L"coordinates"

/**
 *	@brief Defines our 'latitude' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LATITUDE L"latitude"

/**
 *	@brief Defines our 'longitude' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_LONGITUDE L"longitude"

/**
 *	@brief Defines our 'password_hist_len' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PASSWORD_HIST_LEN L"password_hist_len"

/**
 *	@brief Defines our 'max_passwd_age' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MAX_PASSWD_AGE L"max_passwd_age"

/**
 *	@brief Defines our 'min_passwd_age' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MIN_PASSWD_AGE L"min_passwd_age"

/**
 *	@brief Defines our 'min_passwd_len' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MIN_PASSWD_LEN L"min_passwd_len"

/**
 *	@brief Defines our 'complexity_requirements' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_COMPLEXITY_REQUIREMENTS L"complexity_requirements"

/**
 *	@brief Defines our 'screen_off_timeout' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SCREEN_OFF_TIMEOUT L"screen_off_timeout"

/**
 *	@brief Defines our 'sleep_timeout' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SLEEP_TIMEOUT L"sleep_timeout"

/**
 *	@brief Defines our 'screen_saver' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SCREEN_SAVER L"screen_saver"

/**
 *	@brief Defines our 'is_secure' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_IS_SECURE L"is_secure"

/**
 *	@brief Defines our 'on_battery' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_ON_BATTERY L"on_battery"

/**
 *	@brief Defines our 'required_password_timeout' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REQUIRED_PASSWORD_TIMEOUT L"required_password_timeout"

/**
 *	@brief Defines our 'retry_internet_services' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_RETRY_INTERNET_SERVICES L"retry_internet_services"

/**
 *	@brief Defines our 'deployment_action' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_DEPLOYMENT_ACTION L"deployment_action"

/**
 *	@brief Defines our 'CNG' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_CONFIG_ENCRYPTION_API_WIN_CNG L"CNG"

/**
 *	@brief Defines our 'CryptoAPI' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_CONFIG_ENCRYPTION_API_WIN_CRYPT L"CryptoAPI"

/**
 *	@brief Defines our 'patches_source' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PATCHES_SOURCE L"patches_source"

/**
 *	@brief Defines our 'synced_profiles' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SYNCED_PROFILES L"synced_profiles"

/**
 *	@brief Defines our 'signing_code' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_SIGNING_CODE L"signing_code"

/**
 *	@brief Defines our 'overall_progress' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_OVERALL_PROGRESS L"overall_progress"

/**
 *	@brief Defines our 'progress' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PROGRESS L"progress"

/**
 *	@brief Defines our 'mode' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MODE L"mode"

/**
 *	@brief Defines our 'managed_by_3rd_party_products' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MANAGED_BY_3RD_PARTY_PRODUCTS L"managed_by_3rd_party_products"

/**
 *	@brief Defines our 'require_user_context' key which is used to describe an API that needs active user to run successfully
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_REQUIRE_USER_CONTEXT L"require_user_context"

/**
 *	@brief Defines our 'start_date' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_START_DATE L"start_date"

/**
 *	@brief Defines our 'end_date' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_END_DATE L"end_date"

/**
 *	@brief Defines our 'preview_patch' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PREVIEW_PATCH L"preview_patch"

/**
 *	@brief Defines our 'multi_factor_unlock' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_MULTI_FACTOR_UNLOCK L"multi_factor_unlock"

/**
 *	@brief Defines our 'pin_enabled' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PIN_ENABLED L"pin_enabled"

/**
 *	@brief Defines our 'face_enabled' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FACE_ENABLED L"face_enabled"

/**
 *	@brief Defines our 'fingerprint_enabled' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FINGERPRINT_ENABLED L"fingerprint_enabled"

/**
 *	@brief Defines our 'get_user_principal_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_GET_USER_PRINCIPAL_NAME L"get_user_principal_name"

/**
 *	@brief Defines our 'user_principal_name' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_USER_PRINCIPAL_NAME L"user_principal_name"

/**
 *	@brief Defines our 'force_install' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FORCE_INSTALL L"force_install"

/**
 *	@brief Defines our 'product_type' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_PRODUCT_TYPE L"product_type"

/**
 *	@brief Defines our 'startup_type' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_STARTUP_TYPE L"startup_type"

/**
 *	@brief Defines our 'fetch_update_repository' key
 *	@ingroup waapi_json_keys
 */
#define WAAPI_KEY_FETCH_UPDATE_REPOSITORY L"fetch_update_repository"
