/****** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT OR YOUR CHANGES WILL BE OVERWRITTEN! ******/
#pragma once
/**	@file wa_api_product_categories.h
 *	@brief Defines the product categories used for product classification.
 *	@defgroup waapi_product_category Product categories
 */

/**
 *	@brief Defines common product classification. This classification includes all product categories
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_ALL 0

/**
 *	@brief Defines public file sharing product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_PUBLIC_FILE_SHARING 1

/**
 *	@brief Defines backup client product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_BACKUP_CLIENT 2

/**
 *	@brief Defines disk encryption product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_DISK_ENCRYPTION 3

/**
 *	@brief Defines antiphishing product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_ANTIPHISHING 4

/**
 *	@brief Defines antimalware product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_ANTIMALWARE 5

/**
 *	@brief Defines browser product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_BROWSER 6

/**
 *	@brief Defines firewall product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_FIREWALL 7

/**
 *	@brief Defines instant messenger product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_INSTANT_MESSENGER 8

/**
 *	@brief Defines cloud storage product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_CLOUD_STORAGE 9

/**
 *	@brief Defines data loss prevention product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_DATA_LOSS_PREVENTION 11

/**
 *	@brief Defines patch management product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_PATCH_MANAGEMENT 12

/**
 *	@brief Defines VPN client product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_VPN_CLIENT 13

/**
 *	@brief Defines Virtual Machine product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_VIRTUAL_MACHINE 14

/**
 *	@brief Defines health agent product classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_HEALTH_AGENT 15

/**
 *	@brief Defines remote desktop control classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_REMOTE_CONTROL 16

/**
 *	@brief Defines a peer to peer application classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_PEER_TO_PEER 17

/**
 *	@brief Defines that the product has an online video and audio conferencing classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_WEB_CONFERENCE 18

/**
 *	@brief Defines that the product does not have an official classification
 *	@ingroup waapi_product_category
 */
#define WAAPI_CATEGORY_UNCLASSIFIED 10
